image: alpine

pages:
  tags: 
    - Self-hosted
  script:
  - apk update && apk add doxygen
  - doxygen doxygen/Doxyfile
  - cp doxygen/documentation/html/ public/
  artifacts:
    paths:
    - public/
  only:
  - master
