image: 
  name: registry.gitlab.com/minecraftchest1/docker-images

test-build:
  script:
    - pwd
    - make
  only:
    - merge_requests
    - external_pull_requests
    - pushes 
    - external_push