.TH "Minecraftchest1.Utils.InputErrorException" 3 "Wed Aug 18 2021" "Minecraftchest1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Minecraftchest1.Utils.InputErrorException
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputErrorException\fP (string message)"
.br
.ti -1c
.RI "\fBInputErrorException\fP (string message, Exception inner)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBInput\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBInputErrorException\fP (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Minecraftchest1 from the source code\&.
